In [7]:
import os
print(os.getcwd())
import sys
import numpy as np
print(len([[1,2],[3,4]]))
a = np.array([[1,2],[3,4]])
print(a[:,1])
print(len(np.array([[1,2],[3,4]])))
sys.path.append('../')

print(sys.path)
import torch
use = torch.tensor([[0],[1],[2],[5]])
choice = torch.tensor([0])
print(use[:,choice])

a = np.arange(27).reshape(3,3,3)
print(a)

d:\2月\pinn_nv\tmp_pinn\ut
2
[2 4]
2
['d:\\2月\\pinn_nv\\tmp_pinn\\ut', 'd:\\ana\\envs\\dl\\python310.zip', 'd:\\ana\\envs\\dl\\DLLs', 'd:\\ana\\envs\\dl\\lib', 'd:\\ana\\envs\\dl', '', 'd:\\ana\\envs\\dl\\lib\\site-packages', 'd:\\ana\\envs\\dl\\lib\\site-packages\\win32', 'd:\\ana\\envs\\dl\\lib\\site-packages\\win32\\lib', 'd:\\ana\\envs\\dl\\lib\\site-packages\\Pythonwin', '../', '../', '../', '../', '../', '../', '../']
tensor([[0],
        [1],
        [2],
        [5]])
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


TypeError: can only concatenate list (not "int") to list